spring.application.name=taskflow
server.servlet.context-path=/api/v1

# Database

spring.datasource.url=jdbc:postgresql://localhost:5432/TaskflowDB
spring.datasource.username=<username>
spring.datasource.password=<password>

#Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-spl=true
spring.jpa.hibernate.properties.format_sql=true

#jwt
jwt.secretKey=<secret-Key>
#e.g. secret-key: skcnekcnwecnedvvkkiopwdl

logging.level.org.springframework.security=DEBUG

#SIGTERM
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration